package model.VO.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 23 22:51:55 PKT 2014
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void updateRecords(String[] ids);

    void make_budget_lines(int pid);
}
