package model.VO;

import java.sql.PreparedStatement;

import java.sql.SQLException;

import model.VO.common.AppModule;

import oracle.jbo.JboException;
import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 23 22:51:18 PKT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for VO_XXSalesPlanningProgram1.
     * @return VO_XXSalesPlanningProgram1
     */
    public VO_XXSalesPlanningProgramImpl getVO_XXSalesPlanningProgram1() {
        return (VO_XXSalesPlanningProgramImpl)findViewObject("VO_XXSalesPlanningProgram1");
    }

    /**
     * Container's getter for VO_XXSalesPlanningPhase1.
     * @return VO_XXSalesPlanningPhase1
     */
    public ViewObjectImpl getVO_XXSalesPlanningPhase1() {
        return (ViewObjectImpl)findViewObject("VO_XXSalesPlanningPhase1");
    }

    /**
     * Container's getter for VO_ARCustomers1.
     * @return VO_ARCustomers1
     */
    public ViewObjectImpl getVO_ARCustomers1() {
        return (ViewObjectImpl)findViewObject("VO_ARCustomers1");
    }

    /**
     * Container's getter for VO_SalesPlanningHeader1.
     * @return VO_SalesPlanningHeader1
     */
    public VO_SalesPlanningHeaderImpl getVO_SalesPlanningHeader1() {
        return (VO_SalesPlanningHeaderImpl)findViewObject("VO_SalesPlanningHeader1");
    }

    /**
     * Container's getter for VO_SalesPlanningLines3.
     * @return VO_SalesPlanningLines3
     */
    public ViewObjectImpl getVO_SalesPlanningLines3() {
        return (ViewObjectImpl)findViewObject("VO_SalesPlanningLines3");
    }

    /**
     * Container's getter for VO_SalesPlanningPoType1.
     * @return VO_SalesPlanningPoType1
     */
    public ViewObjectImpl getVO_SalesPlanningPoType1() {
        return (ViewObjectImpl)findViewObject("VO_SalesPlanningPoType1");
    }

    /**
     * Container's getter for VO_SalesPlanningShipMode1.
     * @return VO_SalesPlanningShipMode1
     */
    public ViewObjectImpl getVO_SalesPlanningShipMode1() {
        return (ViewObjectImpl)findViewObject("VO_SalesPlanningShipMode1");
    }

    /**
     * Container's getter for VO_SalesPlanningBookMonth1.
     * @return VO_SalesPlanningBookMonth1
     */
    public ViewObjectImpl getVO_SalesPlanningBookMonth1() {
        return (ViewObjectImpl)findViewObject("VO_SalesPlanningBookMonth1");
    }

    /**
     * Container's getter for VO_SalesPlanningCurrencyCode1.
     * @return VO_SalesPlanningCurrencyCode1
     */
    public ViewObjectImpl getVO_SalesPlanningCurrencyCode1() {
        return (ViewObjectImpl)findViewObject("VO_SalesPlanningCurrencyCode1");
    }

    /**
     * Container's getter for VO_SalesPlanningShipTerm1.
     * @return VO_SalesPlanningShipTerm1
     */
    public ViewObjectImpl getVO_SalesPlanningShipTerm1() {
        return (ViewObjectImpl)findViewObject("VO_SalesPlanningShipTerm1");
    }

    /**
     * Container's getter for VO_SalesPlanningYesNo1.
     * @return VO_SalesPlanningYesNo1
     */
    public ViewObjectImpl getVO_SalesPlanningYesNo1() {
        return (ViewObjectImpl)findViewObject("VO_SalesPlanningYesNo1");
    }

    /**
     * Container's getter for VO_SalesPlanningPOStatus1.
     * @return VO_SalesPlanningPOStatus1
     */
    public ViewObjectImpl getVO_SalesPlanningPOStatus1() {
        return (ViewObjectImpl)findViewObject("VO_SalesPlanningPOStatus1");
    }

    /**
     * Container's getter for VO_SelectedCustName1.
     * @return VO_SelectedCustName1
     */
    public VO_SelectedCustNameImpl getVO_SelectedCustName1() {
        return (VO_SelectedCustNameImpl)findViewObject("VO_SelectedCustName1");
    }

    /**
     * Container's getter for VO_SelectedCustPoNo1.
     * @return VO_SelectedCustPoNo1
     */
    public VO_SelectedCustPoNoImpl getVO_SelectedCustPoNo1() {
        return (VO_SelectedCustPoNoImpl)findViewObject("VO_SelectedCustPoNo1");
    }

    /**
     * Container's getter for VO_SelectedSalesContractNo1.
     * @return VO_SelectedSalesContractNo1
     */
    public VO_SelectedSalesContractNoImpl getVO_SelectedSalesContractNo1() {
        return (VO_SelectedSalesContractNoImpl)findViewObject("VO_SelectedSalesContractNo1");
    }

    /**
     * Container's getter for VO_SelectedDyeingWoNo1.
     * @return VO_SelectedDyeingWoNo1
     */
    public VO_SelectedDyeingWoNoImpl getVO_SelectedDyeingWoNo1() {
        return (VO_SelectedDyeingWoNoImpl)findViewObject("VO_SelectedDyeingWoNo1");
    }

    /**
     * Container's getter for VO_SelectedGriageContractNo1.
     * @return VO_SelectedGriageContractNo1
     */
    public VO_SelectedGriageContractNoImpl getVO_SelectedGriageContractNo1() {
        return (VO_SelectedGriageContractNoImpl)findViewObject("VO_SelectedGriageContractNo1");
    }

    /**
     * Container's getter for VO_SalesPlanningHeader2.
     * @return VO_SalesPlanningHeader2
     */
    public VO_SalesPlanningHeaderImpl getVO_SalesPlanningHeader2() {
        return (VO_SalesPlanningHeaderImpl)findViewObject("VO_SalesPlanningHeader2");
    }

    /**
     * Container's getter for VO_SalesPlanningLines1.
     * @return VO_SalesPlanningLines1
     */
    public ViewObjectImpl getVO_SalesPlanningLines1() {
        return (ViewObjectImpl)findViewObject("VO_SalesPlanningLines1");
    }

    /**
     * Container's getter for VO_SalesPlanningHeader3.
     * @return VO_SalesPlanningHeader3
     */
    public VO_SalesPlanningHeaderImpl getVO_SalesPlanningHeader3() {
        return (VO_SalesPlanningHeaderImpl)findViewObject("VO_SalesPlanningHeader3");
    }

    /**
     * Container's getter for VO_SalesPlanningLines2.
     * @return VO_SalesPlanningLines2
     */
    public ViewObjectImpl getVO_SalesPlanningLines2() {
        return (ViewObjectImpl)findViewObject("VO_SalesPlanningLines2");
    }

    /**
     * Container's getter for VO_SalesPlanningArticle1.
     * @return VO_SalesPlanningArticle1
     */
    public ViewObjectImpl getVO_SalesPlanningArticle1() {
        return (ViewObjectImpl)findViewObject("VO_SalesPlanningArticle1");
    }

    /**
     * Container's getter for VO_XXSalesPlanningHeaderMgt1.
     * @return VO_XXSalesPlanningHeaderMgt1
     */
    public VO_XXSalesPlanningHeaderMgtImpl getVO_XXSalesPlanningHeaderMgt1() {
        return (VO_XXSalesPlanningHeaderMgtImpl)findViewObject("VO_XXSalesPlanningHeaderMgt1");
    }

    /**
     * Container's getter for VO_SalesPlanningHeader4.
     * @return VO_SalesPlanningHeader4
     */
    public VO_SalesPlanningHeaderImpl getVO_SalesPlanningHeader4() {
        return (VO_SalesPlanningHeaderImpl)findViewObject("VO_SalesPlanningHeader4");
    }

    /**
     * Container's getter for VO_SalesPlanningLines4.
     * @return VO_SalesPlanningLines4
     */
    public ViewObjectImpl getVO_SalesPlanningLines4() {
        return (ViewObjectImpl)findViewObject("VO_SalesPlanningLines4");
    }

    /**
     * Container's getter for VO_XXSalesPlanningHeaderMgt2.
     * @return VO_XXSalesPlanningHeaderMgt2
     */
    public VO_XXSalesPlanningHeaderMgtImpl getVO_XXSalesPlanningHeaderMgt2() {
        return (VO_XXSalesPlanningHeaderMgtImpl)findViewObject("VO_XXSalesPlanningHeaderMgt2");
    }

    /**
     * Container's getter for VO_SalesPlanningLines5.
     * @return VO_SalesPlanningLines5
     */
    public ViewObjectImpl getVO_SalesPlanningLines5() {
        return (ViewObjectImpl)findViewObject("VO_SalesPlanningLines5");
    }

    /**
     * Container's getter for VO_OldManager1.
     * @return VO_OldManager1
     */
    public ViewObjectImpl getVO_OldManager1() {
        return (ViewObjectImpl)findViewObject("VO_OldManager1");
    }

    /**
     * Container's getter for VO_NewManager1.
     * @return VO_NewManager1
     */
    public ViewObjectImpl getVO_NewManager1() {
        return (ViewObjectImpl)findViewObject("VO_NewManager1");
    }

    /**
     * Container's getter for VL_HeaderLines.
     * @return VL_HeaderLines
     */
    public ViewLinkImpl getVL_HeaderLines() {
        return (ViewLinkImpl)findViewLink("VL_HeaderLines");
    }

    /**
     * Container's getter for VL_HeadLine.
     * @return VL_HeadLine
     */
    public ViewLinkImpl getVL_HeadLine() {
        return (ViewLinkImpl)findViewLink("VL_HeadLine");
    }

    /**
     * Container's getter for VL_LinesHeaderMgt.
     * @return VL_LinesHeaderMgt
     */
    public ViewLinkImpl getVL_LinesHeaderMgt() {
        return (ViewLinkImpl)findViewLink("VL_LinesHeaderMgt");
    }

    public void updateRecords(String[] ids) {
        String old = "3750";
        String New = "3771";
        
        String oldid = ids[0];
        String newid = ids[1];
        
        ViewObjectImpl view = getVO_XXSalesPlanningProgramUpdate1();
        long count = view.getEstimatedRowCount();
        System.out.println("count: " + count);
        Row r = view.next();
        while (r != null) {
            if (r.getAttribute("ProgramManager") != null) {
                System.out.println(r.getAttribute("ProgramManager"));
                if (r.getAttribute("ProgramManager").toString().equals(oldid)) {
                    System.out.println("Update this");
                    r.setAttribute("ProgramManager", newid);
                }
            }
            r = view.next();
        }
    }
    
    public void make_budget_lines(int pid){
        PreparedStatement st = null;
                Object[] bindVariables = { pid };
                try {
                    st =
         getDBTransaction().createPreparedStatement("begin make_budget_lines(?) ;end;", 0);


                    st.setObject(1, pid);
                    

                    st.executeUpdate();
                   
                } catch (SQLException e) {
                    throw new JboException(e);
                } finally {
                    if (st != null) {
                        try {
                            // 5. Close the statement
                            st.close();
                            if (st.isClosed()) {
                                System.out.println("AppModuleImpl.java: PrepaidStatement closed");
                            }
//                            st.getConnection().close();
//                            
//                            if (st.getConnection().isClosed()) {
//                                System.out.println("AppModuleImpl.java: Connection is closed");
//                            }
                            
                        } catch (SQLException e) {
                            System.out.println("AppModuleImple.java: "+e.getMessage());
                        }
                    }
                }
    }

    /**
     * Container's getter for VO_XXSalesPlanningProgramUpdate1.
     * @return VO_XXSalesPlanningProgramUpdate1
     */
    public ViewObjectImpl getVO_XXSalesPlanningProgramUpdate1() {
        return (ViewObjectImpl)findViewObject("VO_XXSalesPlanningProgramUpdate1");
    }

    /**
     * Container's getter for VO_XXSppArticle1.
     * @return VO_XXSppArticle1
     */
    public ViewObjectImpl getVO_XXSppArticle1() {
        return (ViewObjectImpl)findViewObject("VO_XXSppArticle1");
    }

    /**
     * Container's getter for VO_XXSalesPlanningProgram2.
     * @return VO_XXSalesPlanningProgram2
     */
    public VO_XXSalesPlanningProgramImpl getVO_XXSalesPlanningProgram2() {
        return (VO_XXSalesPlanningProgramImpl)findViewObject("VO_XXSalesPlanningProgram2");
    }

    /**
     * Container's getter for VO_XXSppArticle2.
     * @return VO_XXSppArticle2
     */
    public ViewObjectImpl getVO_XXSppArticle2() {
        return (ViewObjectImpl)findViewObject("VO_XXSppArticle2");
    }

    /**
     * Container's getter for VL_ProgramArticle.
     * @return VL_ProgramArticle
     */
    public ViewLinkImpl getVL_ProgramArticle() {
        return (ViewLinkImpl)findViewLink("VL_ProgramArticle");
    }

    /**
     * Container's getter for LOV_XXSppArticle1.
     * @return LOV_XXSppArticle1
     */
    public ViewObjectImpl getLOV_XXSppArticle1() {
        return (ViewObjectImpl)findViewObject("LOV_XXSppArticle1");
    }

    /**
     * Container's getter for VO_XXSppSize1.
     * @return VO_XXSppSize1
     */
    public ViewObjectImpl getVO_XXSppSize1() {
        return (ViewObjectImpl)findViewObject("VO_XXSppSize1");
    }

    /**
     * Container's getter for LOV_XXSppSize1.
     * @return LOV_XXSppSize1
     */
    public ViewObjectImpl getLOV_XXSppSize1() {
        return (ViewObjectImpl)findViewObject("LOV_XXSppSize1");
    }

    /**
     * Container's getter for VO_XXSalesPlanningProgram3.
     * @return VO_XXSalesPlanningProgram3
     */
    public VO_XXSalesPlanningProgramImpl getVO_XXSalesPlanningProgram3() {
        return (VO_XXSalesPlanningProgramImpl)findViewObject("VO_XXSalesPlanningProgram3");
    }

    /**
     * Container's getter for VO_XXSppSize2.
     * @return VO_XXSppSize2
     */
    public ViewObjectImpl getVO_XXSppSize2() {
        return (ViewObjectImpl)findViewObject("VO_XXSppSize2");
    }

    /**
     * Container's getter for VL_ProgramSize.
     * @return VL_ProgramSize
     */
    public ViewLinkImpl getVL_ProgramSize() {
        return (ViewLinkImpl)findViewLink("VL_ProgramSize");
    }

    /**
     * Container's getter for VO_XXSppColor1.
     * @return VO_XXSppColor1
     */
    public ViewObjectImpl getVO_XXSppColor1() {
        return (ViewObjectImpl)findViewObject("VO_XXSppColor1");
    }

    /**
     * Container's getter for LOV_XXSppColor1.
     * @return LOV_XXSppColor1
     */
    public ViewObjectImpl getLOV_XXSppColor1() {
        return (ViewObjectImpl)findViewObject("LOV_XXSppColor1");
    }

    /**
     * Container's getter for VO_XXSalesPlanningProgram4.
     * @return VO_XXSalesPlanningProgram4
     */
    public VO_XXSalesPlanningProgramImpl getVO_XXSalesPlanningProgram4() {
        return (VO_XXSalesPlanningProgramImpl)findViewObject("VO_XXSalesPlanningProgram4");
    }

    /**
     * Container's getter for VO_XXSppColor2.
     * @return VO_XXSppColor2
     */
    public ViewObjectImpl getVO_XXSppColor2() {
        return (ViewObjectImpl)findViewObject("VO_XXSppColor2");
    }

    /**
     * Container's getter for VL_ProgramColor.
     * @return VL_ProgramColor
     */
    public ViewLinkImpl getVL_ProgramColor() {
        return (ViewLinkImpl)findViewLink("VL_ProgramColor");
    }

    /**
     * Container's getter for VOExmillCalander1.
     * @return VOExmillCalander1
     */
    public ViewObjectImpl getVOExmillCalander1() {
        return (ViewObjectImpl)findViewObject("VOExmillCalander1");
    }

    /**
     * Container's getter for VO_SalesPlanningHeaderNew1.
     * @return VO_SalesPlanningHeaderNew1
     */
    public ViewObjectImpl getVO_SalesPlanningHeaderNew1() {
        return (ViewObjectImpl)findViewObject("VO_SalesPlanningHeaderNew1");
    }
}
