package model.VO;

import HandlerBean.Bunny;

import HandlerBean.PageListener;

import HandlerBean.UserInfo;

import javax.faces.context.FacesContext;

import javax.servlet.http.HttpServletRequest;

import model.EO.EO_SalesPlanningHeaderImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 01 21:48:01 UZT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_SalesPlanningHeaderRowImpl extends ViewRowImpl {
    FacesContext fctx;
    HttpServletRequest req;
    
    @Override
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        fctx = FacesContext.getCurrentInstance();
        req =
        (HttpServletRequest)fctx.getExternalContext().getRequest();
        
        
        setCreatedBy((String)req.getSession().getAttribute("userID"));
        setLastUpdatedBy((String)req.getSession().getAttribute("userID"));
    }
   

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Accessories,
        AccessoriesOrderDate,
        BookMonth,
        BookingMonth,
        ContainerBooked,
        ContainerBookingDate,
        CreatedBy,
        CreationDate,
        CstkPl,
        CurrencyCode,
        CustPoNo,
        DyeingInputDate,
        DyeingStatus,
        DyeingWoNo,
        ExMill,
        GreigeCompletionDate,
        GreigeContractNo,
        InspectionDate,
        InspectionDone,
        LastUpdateDate,
        LastUpdatedBy,
        LcStatus,
        Ner,
        PoRecDate,
        PoStatusLookupCode,
        PoType,
        ProgramId,
        Bags,
        NormalThread,
        SylkoThread,
        ElasticCordFusing,
        InhouseStickers,
        Misc,
        ImportedMisc,
        Carton,
        Stiffers,
        CareLabel,
        Inserts,
        Remarks,
        SalesContractNo,
        ShipMode,
        ShipTerm,
        ShipmentDate,
        SpHeaderId,
        StitchInputDate,
        Value,
        VersionNumber,
        ViewerNote,
        ThirdPartyAudit,
        Article,
        ProgramName,
        ProgramManager,
        Customer,
        CustomerName,
        ProgramPhase,
        Potypemeaning,
        ShipModeL,
        Lastupdatedbyuser,
        Createdbyuser,
        PoStatus,
        Delivery,
        MoNo,
        VO_SalesPlanningLines1,
        VO_SalesPlanningLines,
        VO_SalesPlanningLines2,
        VO_XXSalesPlanningProgram1,
        VO_SalesPlanningPoType1,
        VO_SalesPlanningShipMode1,
        VO_SalesPlanningBookMonth1,
        VO_SalesPlanningCurrencyCode1,
        VO_SalesPlanningShipTerm1,
        VO_SalesPlanningYesNo1,
        VO_SalesPlanningPOStatus1,
        VO_SalesPlanningHeader1,
        VO_SelectedCustName1,
        VO_SelectedCustPoNo1,
        VO_SelectedSalesContractNo1,
        VO_SelectedDyeingWoNo1,
        VO_SelectedGriageContractNo1,
        VO_XXSalesPlanningPhase1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ACCESSORIES = AttributesEnum.Accessories.index();
    public static final int ACCESSORIESORDERDATE = AttributesEnum.AccessoriesOrderDate.index();
    public static final int BOOKMONTH = AttributesEnum.BookMonth.index();
    public static final int BOOKINGMONTH = AttributesEnum.BookingMonth.index();
    public static final int CONTAINERBOOKED = AttributesEnum.ContainerBooked.index();
    public static final int CONTAINERBOOKINGDATE = AttributesEnum.ContainerBookingDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CSTKPL = AttributesEnum.CstkPl.index();
    public static final int CURRENCYCODE = AttributesEnum.CurrencyCode.index();
    public static final int CUSTPONO = AttributesEnum.CustPoNo.index();
    public static final int DYEINGINPUTDATE = AttributesEnum.DyeingInputDate.index();
    public static final int DYEINGSTATUS = AttributesEnum.DyeingStatus.index();
    public static final int DYEINGWONO = AttributesEnum.DyeingWoNo.index();
    public static final int EXMILL = AttributesEnum.ExMill.index();
    public static final int GREIGECOMPLETIONDATE = AttributesEnum.GreigeCompletionDate.index();
    public static final int GREIGECONTRACTNO = AttributesEnum.GreigeContractNo.index();
    public static final int INSPECTIONDATE = AttributesEnum.InspectionDate.index();
    public static final int INSPECTIONDONE = AttributesEnum.InspectionDone.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LCSTATUS = AttributesEnum.LcStatus.index();
    public static final int NER = AttributesEnum.Ner.index();
    public static final int PORECDATE = AttributesEnum.PoRecDate.index();
    public static final int POSTATUSLOOKUPCODE = AttributesEnum.PoStatusLookupCode.index();
    public static final int POTYPE = AttributesEnum.PoType.index();
    public static final int PROGRAMID = AttributesEnum.ProgramId.index();
    public static final int BAGS = AttributesEnum.Bags.index();
    public static final int NORMALTHREAD = AttributesEnum.NormalThread.index();
    public static final int SYLKOTHREAD = AttributesEnum.SylkoThread.index();
    public static final int ELASTICCORDFUSING = AttributesEnum.ElasticCordFusing.index();
    public static final int INHOUSESTICKERS = AttributesEnum.InhouseStickers.index();
    public static final int MISC = AttributesEnum.Misc.index();
    public static final int IMPORTEDMISC = AttributesEnum.ImportedMisc.index();
    public static final int CARTON = AttributesEnum.Carton.index();
    public static final int STIFFERS = AttributesEnum.Stiffers.index();
    public static final int CARELABEL = AttributesEnum.CareLabel.index();
    public static final int INSERTS = AttributesEnum.Inserts.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int SALESCONTRACTNO = AttributesEnum.SalesContractNo.index();
    public static final int SHIPMODE = AttributesEnum.ShipMode.index();
    public static final int SHIPTERM = AttributesEnum.ShipTerm.index();
    public static final int SHIPMENTDATE = AttributesEnum.ShipmentDate.index();
    public static final int SPHEADERID = AttributesEnum.SpHeaderId.index();
    public static final int STITCHINPUTDATE = AttributesEnum.StitchInputDate.index();
    public static final int VALUE = AttributesEnum.Value.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();
    public static final int VIEWERNOTE = AttributesEnum.ViewerNote.index();
    public static final int THIRDPARTYAUDIT = AttributesEnum.ThirdPartyAudit.index();
    public static final int ARTICLE = AttributesEnum.Article.index();
    public static final int PROGRAMNAME = AttributesEnum.ProgramName.index();
    public static final int PROGRAMMANAGER = AttributesEnum.ProgramManager.index();
    public static final int CUSTOMER = AttributesEnum.Customer.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int PROGRAMPHASE = AttributesEnum.ProgramPhase.index();
    public static final int POTYPEMEANING = AttributesEnum.Potypemeaning.index();
    public static final int SHIPMODEL = AttributesEnum.ShipModeL.index();
    public static final int LASTUPDATEDBYUSER = AttributesEnum.Lastupdatedbyuser.index();
    public static final int CREATEDBYUSER = AttributesEnum.Createdbyuser.index();
    public static final int POSTATUS = AttributesEnum.PoStatus.index();
    public static final int DELIVERY = AttributesEnum.Delivery.index();
    public static final int MONO = AttributesEnum.MoNo.index();
    public static final int VO_SALESPLANNINGLINES1 = AttributesEnum.VO_SalesPlanningLines1.index();
    public static final int VO_SALESPLANNINGLINES = AttributesEnum.VO_SalesPlanningLines.index();
    public static final int VO_SALESPLANNINGLINES2 = AttributesEnum.VO_SalesPlanningLines2.index();
    public static final int VO_XXSALESPLANNINGPROGRAM1 = AttributesEnum.VO_XXSalesPlanningProgram1.index();
    public static final int VO_SALESPLANNINGPOTYPE1 = AttributesEnum.VO_SalesPlanningPoType1.index();
    public static final int VO_SALESPLANNINGSHIPMODE1 = AttributesEnum.VO_SalesPlanningShipMode1.index();
    public static final int VO_SALESPLANNINGBOOKMONTH1 = AttributesEnum.VO_SalesPlanningBookMonth1.index();
    public static final int VO_SALESPLANNINGCURRENCYCODE1 = AttributesEnum.VO_SalesPlanningCurrencyCode1.index();
    public static final int VO_SALESPLANNINGSHIPTERM1 = AttributesEnum.VO_SalesPlanningShipTerm1.index();
    public static final int VO_SALESPLANNINGYESNO1 = AttributesEnum.VO_SalesPlanningYesNo1.index();
    public static final int VO_SALESPLANNINGPOSTATUS1 = AttributesEnum.VO_SalesPlanningPOStatus1.index();
    public static final int VO_SALESPLANNINGHEADER1 = AttributesEnum.VO_SalesPlanningHeader1.index();
    public static final int VO_SELECTEDCUSTNAME1 = AttributesEnum.VO_SelectedCustName1.index();
    public static final int VO_SELECTEDCUSTPONO1 = AttributesEnum.VO_SelectedCustPoNo1.index();
    public static final int VO_SELECTEDSALESCONTRACTNO1 = AttributesEnum.VO_SelectedSalesContractNo1.index();
    public static final int VO_SELECTEDDYEINGWONO1 = AttributesEnum.VO_SelectedDyeingWoNo1.index();
    public static final int VO_SELECTEDGRIAGECONTRACTNO1 = AttributesEnum.VO_SelectedGriageContractNo1.index();
    public static final int VO_XXSALESPLANNINGPHASE1 = AttributesEnum.VO_XXSalesPlanningPhase1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VO_SalesPlanningHeaderRowImpl() {
    }

    /**
     * Gets EO_SalesPlanningHeader entity object.
     * @return the EO_SalesPlanningHeader
     */
    public EO_SalesPlanningHeaderImpl getEO_SalesPlanningHeader() {
        return (EO_SalesPlanningHeaderImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for ACCESSORIES using the alias name Accessories.
     * @return the ACCESSORIES
     */
    public String getAccessories() {
        return (String) getAttributeInternal(ACCESSORIES);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCESSORIES using the alias name Accessories.
     * @param value value to set the ACCESSORIES
     */
    public void setAccessories(String value) {
        setAttributeInternal(ACCESSORIES, value);
    }

    /**
     * Gets the attribute value for ACCESSORIES_ORDER_DATE using the alias name AccessoriesOrderDate.
     * @return the ACCESSORIES_ORDER_DATE
     */
    public Date getAccessoriesOrderDate() {
        return (Date) getAttributeInternal(ACCESSORIESORDERDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCESSORIES_ORDER_DATE using the alias name AccessoriesOrderDate.
     * @param value value to set the ACCESSORIES_ORDER_DATE
     */
    public void setAccessoriesOrderDate(Date value) {
        setAttributeInternal(ACCESSORIESORDERDATE, value);
    }

    /**
     * Gets the attribute value for BOOK_MONTH using the alias name BookMonth.
     * @return the BOOK_MONTH
     */
    public String getBookMonth() {
        return (String) getAttributeInternal(BOOKMONTH);
    }

    /**
     * Sets <code>value</code> as attribute value for BOOK_MONTH using the alias name BookMonth.
     * @param value value to set the BOOK_MONTH
     */
    public void setBookMonth(String value) {
        setAttributeInternal(BOOKMONTH, value);
    }

    /**
     * Gets the attribute value for BOOKING_MONTH using the alias name BookingMonth.
     * @return the BOOKING_MONTH
     */
    public Date getBookingMonth() {
        return (Date) getAttributeInternal(BOOKINGMONTH);
    }

    /**
     * Sets <code>value</code> as attribute value for BOOKING_MONTH using the alias name BookingMonth.
     * @param value value to set the BOOKING_MONTH
     */
    public void setBookingMonth(Date value) {
        setAttributeInternal(BOOKINGMONTH, value);
    }

    /**
     * Gets the attribute value for CONTAINER_BOOKED using the alias name ContainerBooked.
     * @return the CONTAINER_BOOKED
     */
    public String getContainerBooked() {
        return (String) getAttributeInternal(CONTAINERBOOKED);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTAINER_BOOKED using the alias name ContainerBooked.
     * @param value value to set the CONTAINER_BOOKED
     */
    public void setContainerBooked(String value) {
        setAttributeInternal(CONTAINERBOOKED, value);
    }

    /**
     * Gets the attribute value for CONTAINER_BOOKING_DATE using the alias name ContainerBookingDate.
     * @return the CONTAINER_BOOKING_DATE
     */
    public Timestamp getContainerBookingDate() {
        return (Timestamp)getAttributeInternal(CONTAINERBOOKINGDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTAINER_BOOKING_DATE using the alias name ContainerBookingDate.
     * @param value value to set the CONTAINER_BOOKING_DATE
     */
    public void setContainerBookingDate(Timestamp value) {
        setAttributeInternal(CONTAINERBOOKINGDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CSTK_PL using the alias name CstkPl.
     * @return the CSTK_PL
     */
    public String getCstkPl() {
        return (String) getAttributeInternal(CSTKPL);
    }

    /**
     * Sets <code>value</code> as attribute value for CSTK_PL using the alias name CstkPl.
     * @param value value to set the CSTK_PL
     */
    public void setCstkPl(String value) {
        setAttributeInternal(CSTKPL, value);
    }

    /**
     * Gets the attribute value for CURRENCY_CODE using the alias name CurrencyCode.
     * @return the CURRENCY_CODE
     */
    public String getCurrencyCode() {
        return (String) getAttributeInternal(CURRENCYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY_CODE using the alias name CurrencyCode.
     * @param value value to set the CURRENCY_CODE
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**
     * Gets the attribute value for CUST_PO_NO using the alias name CustPoNo.
     * @return the CUST_PO_NO
     */
    public String getCustPoNo() {
        return (String) getAttributeInternal(CUSTPONO);
    }

    /**
     * Sets <code>value</code> as attribute value for CUST_PO_NO using the alias name CustPoNo.
     * @param value value to set the CUST_PO_NO
     */
    public void setCustPoNo(String value) {
        setAttributeInternal(CUSTPONO, value);
    }

    /**
     * Gets the attribute value for DYEING_INPUT_DATE using the alias name DyeingInputDate.
     * @return the DYEING_INPUT_DATE
     */
    public Date getDyeingInputDate() {
        return (Date) getAttributeInternal(DYEINGINPUTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DYEING_INPUT_DATE using the alias name DyeingInputDate.
     * @param value value to set the DYEING_INPUT_DATE
     */
    public void setDyeingInputDate(Date value) {
        setAttributeInternal(DYEINGINPUTDATE, value);
    }

    /**
     * Gets the attribute value for DYEING_STATUS using the alias name DyeingStatus.
     * @return the DYEING_STATUS
     */
    public String getDyeingStatus() {
        return (String) getAttributeInternal(DYEINGSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for DYEING_STATUS using the alias name DyeingStatus.
     * @param value value to set the DYEING_STATUS
     */
    public void setDyeingStatus(String value) {
        setAttributeInternal(DYEINGSTATUS, value);
    }

    /**
     * Gets the attribute value for DYEING_WO_NO using the alias name DyeingWoNo.
     * @return the DYEING_WO_NO
     */
    public String getDyeingWoNo() {
        return (String) getAttributeInternal(DYEINGWONO);
    }

    /**
     * Sets <code>value</code> as attribute value for DYEING_WO_NO using the alias name DyeingWoNo.
     * @param value value to set the DYEING_WO_NO
     */
    public void setDyeingWoNo(String value) {
        setAttributeInternal(DYEINGWONO, value);
    }

    /**
     * Gets the attribute value for EX_MILL using the alias name ExMill.
     * @return the EX_MILL
     */
    public Timestamp getExMill() {
        return (Timestamp)getAttributeInternal(EXMILL);
    }

    /**
     * Sets <code>value</code> as attribute value for EX_MILL using the alias name ExMill.
     * @param value value to set the EX_MILL
     */
    public void setExMill(Timestamp value) {
        setAttributeInternal(EXMILL, value);
    }

    /**
     * Gets the attribute value for GREIGE_COMPLETION_DATE using the alias name GreigeCompletionDate.
     * @return the GREIGE_COMPLETION_DATE
     */
    public Date getGreigeCompletionDate() {
        return (Date) getAttributeInternal(GREIGECOMPLETIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GREIGE_COMPLETION_DATE using the alias name GreigeCompletionDate.
     * @param value value to set the GREIGE_COMPLETION_DATE
     */
    public void setGreigeCompletionDate(Date value) {
        setAttributeInternal(GREIGECOMPLETIONDATE, value);
    }

    /**
     * Gets the attribute value for GREIGE_CONTRACT_NO using the alias name GreigeContractNo.
     * @return the GREIGE_CONTRACT_NO
     */
    public String getGreigeContractNo() {
        return (String) getAttributeInternal(GREIGECONTRACTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GREIGE_CONTRACT_NO using the alias name GreigeContractNo.
     * @param value value to set the GREIGE_CONTRACT_NO
     */
    public void setGreigeContractNo(String value) {
        setAttributeInternal(GREIGECONTRACTNO, value);
    }

    /**
     * Gets the attribute value for INSPECTION_DATE using the alias name InspectionDate.
     * @return the INSPECTION_DATE
     */
    public Timestamp getInspectionDate() {
        return (Timestamp)getAttributeInternal(INSPECTIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for INSPECTION_DATE using the alias name InspectionDate.
     * @param value value to set the INSPECTION_DATE
     */
    public void setInspectionDate(Timestamp value) {
        setAttributeInternal(INSPECTIONDATE, value);
    }

    /**
     * Gets the attribute value for INSPECTION_DONE using the alias name InspectionDone.
     * @return the INSPECTION_DONE
     */
    public String getInspectionDone() {
        return (String) getAttributeInternal(INSPECTIONDONE);
    }

    /**
     * Sets <code>value</code> as attribute value for INSPECTION_DONE using the alias name InspectionDone.
     * @param value value to set the INSPECTION_DONE
     */
    public void setInspectionDone(String value) {
        setAttributeInternal(INSPECTIONDONE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LC_STATUS using the alias name LcStatus.
     * @return the LC_STATUS
     */
    public String getLcStatus() {
        return (String) getAttributeInternal(LCSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for LC_STATUS using the alias name LcStatus.
     * @param value value to set the LC_STATUS
     */
    public void setLcStatus(String value) {
        setAttributeInternal(LCSTATUS, value);
    }

    /**
     * Gets the attribute value for NER using the alias name Ner.
     * @return the NER
     */
    public String getNer() {
        return (String) getAttributeInternal(NER);
    }

    /**
     * Sets <code>value</code> as attribute value for NER using the alias name Ner.
     * @param value value to set the NER
     */
    public void setNer(String value) {
        setAttributeInternal(NER, value);
    }

    /**
     * Gets the attribute value for PO_REC_DATE using the alias name PoRecDate.
     * @return the PO_REC_DATE
     */
    public Date getPoRecDate() {
        return (Date) getAttributeInternal(PORECDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_REC_DATE using the alias name PoRecDate.
     * @param value value to set the PO_REC_DATE
     */
    public void setPoRecDate(Date value) {
        setAttributeInternal(PORECDATE, value);
    }

    /**
     * Gets the attribute value for PO_STATUS_LOOKUP_CODE using the alias name PoStatusLookupCode.
     * @return the PO_STATUS_LOOKUP_CODE
     */
    public String getPoStatusLookupCode() {
        return (String) getAttributeInternal(POSTATUSLOOKUPCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_STATUS_LOOKUP_CODE using the alias name PoStatusLookupCode.
     * @param value value to set the PO_STATUS_LOOKUP_CODE
     */
    public void setPoStatusLookupCode(String value) {
        setAttributeInternal(POSTATUSLOOKUPCODE, value);
    }

    /**
     * Gets the attribute value for PO_TYPE using the alias name PoType.
     * @return the PO_TYPE
     */
    public String getPoType() {
        return (String) getAttributeInternal(POTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_TYPE using the alias name PoType.
     * @param value value to set the PO_TYPE
     */
    public void setPoType(String value) {
        setAttributeInternal(POTYPE, value);
    }

    /**
     * Gets the attribute value for PROGRAM_ID using the alias name ProgramId.
     * @return the PROGRAM_ID
     */
    public Number getProgramId() {
        return (Number) getAttributeInternal(PROGRAMID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROGRAM_ID using the alias name ProgramId.
     * @param value value to set the PROGRAM_ID
     */
    public void setProgramId(Number value) {
        setAttributeInternal(PROGRAMID, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for SALES_CONTRACT_NO using the alias name SalesContractNo.
     * @return the SALES_CONTRACT_NO
     */
    public String getSalesContractNo() {
        return (String) getAttributeInternal(SALESCONTRACTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SALES_CONTRACT_NO using the alias name SalesContractNo.
     * @param value value to set the SALES_CONTRACT_NO
     */
    public void setSalesContractNo(String value) {
        setAttributeInternal(SALESCONTRACTNO, value);
    }

    /**
     * Gets the attribute value for SHIP_MODE using the alias name ShipMode.
     * @return the SHIP_MODE
     */
    public String getShipMode() {
        return (String) getAttributeInternal(SHIPMODE);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_MODE using the alias name ShipMode.
     * @param value value to set the SHIP_MODE
     */
    public void setShipMode(String value) {
        setAttributeInternal(SHIPMODE, value);
    }

    /**
     * Gets the attribute value for SHIP_TERM using the alias name ShipTerm.
     * @return the SHIP_TERM
     */
    public String getShipTerm() {
        return (String) getAttributeInternal(SHIPTERM);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_TERM using the alias name ShipTerm.
     * @param value value to set the SHIP_TERM
     */
    public void setShipTerm(String value) {
        setAttributeInternal(SHIPTERM, value);
    }

    /**
     * Gets the attribute value for SHIPMENT_DATE using the alias name ShipmentDate.
     * @return the SHIPMENT_DATE
     */
    public Date getShipmentDate() {
        return (Date) getAttributeInternal(SHIPMENTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPMENT_DATE using the alias name ShipmentDate.
     * @param value value to set the SHIPMENT_DATE
     */
    public void setShipmentDate(Date value) {
        setAttributeInternal(SHIPMENTDATE, value);
    }

    /**
     * Gets the attribute value for SP_HEADER_ID using the alias name SpHeaderId.
     * @return the SP_HEADER_ID
     */
    public Number getSpHeaderId() {
        return (Number) getAttributeInternal(SPHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SP_HEADER_ID using the alias name SpHeaderId.
     * @param value value to set the SP_HEADER_ID
     */
    public void setSpHeaderId(Number value) {
        setAttributeInternal(SPHEADERID, value);
    }

    /**
     * Gets the attribute value for STITCH_INPUT_DATE using the alias name StitchInputDate.
     * @return the STITCH_INPUT_DATE
     */
    public Date getStitchInputDate() {
        return (Date) getAttributeInternal(STITCHINPUTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for STITCH_INPUT_DATE using the alias name StitchInputDate.
     * @param value value to set the STITCH_INPUT_DATE
     */
    public void setStitchInputDate(Date value) {
        setAttributeInternal(STITCHINPUTDATE, value);
    }

    /**
     * Gets the attribute value for VALUE using the alias name Value.
     * @return the VALUE
     */
    public Number getValue() {
        return (Number) getAttributeInternal(VALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for VALUE using the alias name Value.
     * @param value value to set the VALUE
     */
    public void setValue(Number value) {
        setAttributeInternal(VALUE, value);
    }

    /**
     * Gets the attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @return the VERSION_NUMBER
     */
    public Number getVersionNumber() {
        return (Number) getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @param value value to set the VERSION_NUMBER
     */
    public void setVersionNumber(Number value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for VIEWER_NOTE using the alias name ViewerNote.
     * @return the VIEWER_NOTE
     */
    public String getViewerNote() {
        return (String) getAttributeInternal(VIEWERNOTE);
    }

    /**
     * Sets <code>value</code> as attribute value for VIEWER_NOTE using the alias name ViewerNote.
     * @param value value to set the VIEWER_NOTE
     */
    public void setViewerNote(String value) {
        setAttributeInternal(VIEWERNOTE, value);
    }


    /**
     * Gets the attribute value for the calculated attribute Article.
     * @return the Article
     */
    public String getArticle() {
        return (String) getAttributeInternal(ARTICLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Article.
     * @param value value to set the  Article
     */
    public void setArticle(String value) {
        setAttributeInternal(ARTICLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProgramName.
     * @return the ProgramName
     */
    public String getProgramName() {
        return (String) getAttributeInternal(PROGRAMNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProgramName.
     * @param value value to set the  ProgramName
     */
    public void setProgramName(String value) {
        setAttributeInternal(PROGRAMNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProgramManager.
     * @return the ProgramManager
     */
    public String getProgramManager() {
        return (String) getAttributeInternal(PROGRAMMANAGER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProgramManager.
     * @param value value to set the  ProgramManager
     */
    public void setProgramManager(String value) {
        setAttributeInternal(PROGRAMMANAGER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Customer.
     * @return the Customer
     */
    public Number getCustomer() {
        return (Number) getAttributeInternal(CUSTOMER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Customer.
     * @param value value to set the  Customer
     */
    public void setCustomer(Number value) {
        setAttributeInternal(CUSTOMER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerName.
     * @return the CustomerName
     */
    public String getCustomerName() {
        return (String) getAttributeInternal(CUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerName.
     * @param value value to set the  CustomerName
     */
    public void setCustomerName(String value) {
        setAttributeInternal(CUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProgramPhase.
     * @return the ProgramPhase
     */
    public String getProgramPhase() {
        return (String) getAttributeInternal(PROGRAMPHASE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProgramPhase.
     * @param value value to set the  ProgramPhase
     */
    public void setProgramPhase(String value) {
        setAttributeInternal(PROGRAMPHASE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Potypemeaning.
     * @return the Potypemeaning
     */
    public String getPotypemeaning() {
        return (String) getAttributeInternal(POTYPEMEANING);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Potypemeaning.
     * @param value value to set the  Potypemeaning
     */
    public void setPotypemeaning(String value) {
        setAttributeInternal(POTYPEMEANING, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ShipModeL.
     * @return the ShipModeL
     */
    public String getShipModeL() {
        return (String) getAttributeInternal(SHIPMODEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ShipModeL.
     * @param value value to set the  ShipModeL
     */
    public void setShipModeL(String value) {
        setAttributeInternal(SHIPMODEL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Lastupdatedbyuser.
     * @return the Lastupdatedbyuser
     */
    public String getLastupdatedbyuser() {
        return (String) getAttributeInternal(LASTUPDATEDBYUSER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Lastupdatedbyuser.
     * @param value value to set the  Lastupdatedbyuser
     */
    public void setLastupdatedbyuser(String value) {
        setAttributeInternal(LASTUPDATEDBYUSER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Createdbyuser.
     * @return the Createdbyuser
     */
    public String getCreatedbyuser() {
        return (String) getAttributeInternal(CREATEDBYUSER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Createdbyuser.
     * @param value value to set the  Createdbyuser
     */
    public void setCreatedbyuser(String value) {
        setAttributeInternal(CREATEDBYUSER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PoStatus.
     * @return the PoStatus
     */
    public String getPoStatus() {
        return (String) getAttributeInternal(POSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PoStatus.
     * @param value value to set the  PoStatus
     */
    public void setPoStatus(String value) {
        setAttributeInternal(POSTATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Delivery.
     * @return the Delivery
     */
    public String getDelivery() {
        return (String) getAttributeInternal(DELIVERY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Delivery.
     * @param value value to set the  Delivery
     */
    public void setDelivery(String value) {
        setAttributeInternal(DELIVERY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MoNo.
     * @return the MoNo
     */
    public String getMoNo() {
        return (String) getAttributeInternal(MONO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MoNo.
     * @param value value to set the  MoNo
     */
    public void setMoNo(String value) {
        setAttributeInternal(MONO, value);
    }


    /**
     * Gets the attribute value for BAGS using the alias name Bags.
     * @return the BAGS
     */
    public String getBags() {
        return (String) getAttributeInternal(BAGS);
    }

    /**
     * Sets <code>value</code> as attribute value for BAGS using the alias name Bags.
     * @param value value to set the BAGS
     */
    public void setBags(String value) {
        setAttributeInternal(BAGS, value);
    }

    /**
     * Gets the attribute value for CARE_LABEL using the alias name CareLabel.
     * @return the CARE_LABEL
     */
    public String getCareLabel() {
        return (String) getAttributeInternal(CARELABEL);
    }

    /**
     * Sets <code>value</code> as attribute value for CARE_LABEL using the alias name CareLabel.
     * @param value value to set the CARE_LABEL
     */
    public void setCareLabel(String value) {
        setAttributeInternal(CARELABEL, value);
    }

    /**
     * Gets the attribute value for ELASTIC_CORD_FUSING using the alias name ElasticCordFusing.
     * @return the ELASTIC_CORD_FUSING
     */
    public String getElasticCordFusing() {
        return (String) getAttributeInternal(ELASTICCORDFUSING);
    }

    /**
     * Sets <code>value</code> as attribute value for ELASTIC_CORD_FUSING using the alias name ElasticCordFusing.
     * @param value value to set the ELASTIC_CORD_FUSING
     */
    public void setElasticCordFusing(String value) {
        setAttributeInternal(ELASTICCORDFUSING, value);
    }

    /**
     * Gets the attribute value for IMPORTED_MISC using the alias name ImportedMisc.
     * @return the IMPORTED_MISC
     */
    public String getImportedMisc() {
        return (String) getAttributeInternal(IMPORTEDMISC);
    }

    /**
     * Sets <code>value</code> as attribute value for IMPORTED_MISC using the alias name ImportedMisc.
     * @param value value to set the IMPORTED_MISC
     */
    public void setImportedMisc(String value) {
        setAttributeInternal(IMPORTEDMISC, value);
    }

    /**
     * Gets the attribute value for INHOUSE_STICKERS using the alias name InhouseStickers.
     * @return the INHOUSE_STICKERS
     */
    public String getInhouseStickers() {
        return (String) getAttributeInternal(INHOUSESTICKERS);
    }

    /**
     * Sets <code>value</code> as attribute value for INHOUSE_STICKERS using the alias name InhouseStickers.
     * @param value value to set the INHOUSE_STICKERS
     */
    public void setInhouseStickers(String value) {
        setAttributeInternal(INHOUSESTICKERS, value);
    }

    /**
     * Gets the attribute value for INSERTS using the alias name Inserts.
     * @return the INSERTS
     */
    public String getInserts() {
        return (String) getAttributeInternal(INSERTS);
    }

    /**
     * Sets <code>value</code> as attribute value for INSERTS using the alias name Inserts.
     * @param value value to set the INSERTS
     */
    public void setInserts(String value) {
        setAttributeInternal(INSERTS, value);
    }

    /**
     * Gets the attribute value for MISC using the alias name Misc.
     * @return the MISC
     */
    public String getMisc() {
        return (String) getAttributeInternal(MISC);
    }

    /**
     * Sets <code>value</code> as attribute value for MISC using the alias name Misc.
     * @param value value to set the MISC
     */
    public void setMisc(String value) {
        setAttributeInternal(MISC, value);
    }

    /**
     * Gets the attribute value for NORMAL_THREAD using the alias name NormalThread.
     * @return the NORMAL_THREAD
     */
    public String getNormalThread() {
        return (String) getAttributeInternal(NORMALTHREAD);
    }

    /**
     * Sets <code>value</code> as attribute value for NORMAL_THREAD using the alias name NormalThread.
     * @param value value to set the NORMAL_THREAD
     */
    public void setNormalThread(String value) {
        setAttributeInternal(NORMALTHREAD, value);
    }

    /**
     * Gets the attribute value for STIFFERS using the alias name Stiffers.
     * @return the STIFFERS
     */
    public String getStiffers() {
        return (String) getAttributeInternal(STIFFERS);
    }

    /**
     * Sets <code>value</code> as attribute value for STIFFERS using the alias name Stiffers.
     * @param value value to set the STIFFERS
     */
    public void setStiffers(String value) {
        setAttributeInternal(STIFFERS, value);
    }

    /**
     * Gets the attribute value for SYLKO_THREAD using the alias name SylkoThread.
     * @return the SYLKO_THREAD
     */
    public String getSylkoThread() {
        return (String) getAttributeInternal(SYLKOTHREAD);
    }

    /**
     * Sets <code>value</code> as attribute value for SYLKO_THREAD using the alias name SylkoThread.
     * @param value value to set the SYLKO_THREAD
     */
    public void setSylkoThread(String value) {
        setAttributeInternal(SYLKOTHREAD, value);
    }

    /**
     * Gets the attribute value for CARTON using the alias name Carton.
     * @return the CARTON
     */
    public String getCarton() {
        return (String) getAttributeInternal(CARTON);
    }

    /**
     * Sets <code>value</code> as attribute value for CARTON using the alias name Carton.
     * @param value value to set the CARTON
     */
    public void setCarton(String value) {
        setAttributeInternal(CARTON, value);
    }

    /**
     * Gets the attribute value for THIRD_PARTY_AUDIT using the alias name ThirdPartyAudit.
     * @return the THIRD_PARTY_AUDIT
     */
    public String getThirdPartyAudit() {
        return (String) getAttributeInternal(THIRDPARTYAUDIT);
    }

    /**
     * Sets <code>value</code> as attribute value for THIRD_PARTY_AUDIT using the alias name ThirdPartyAudit.
     * @param value value to set the THIRD_PARTY_AUDIT
     */
    public void setThirdPartyAudit(String value) {
        setAttributeInternal(THIRDPARTYAUDIT, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link VO_SalesPlanningLines1.
     */
    public RowIterator getVO_SalesPlanningLines1() {
        return (RowIterator)getAttributeInternal(VO_SALESPLANNINGLINES1);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link VO_SalesPlanningLines.
     */
    public RowIterator getVO_SalesPlanningLines() {
        return (RowIterator)getAttributeInternal(VO_SALESPLANNINGLINES);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link VO_SalesPlanningLines2.
     */
    public RowIterator getVO_SalesPlanningLines2() {
        return (RowIterator)getAttributeInternal(VO_SALESPLANNINGLINES2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_XXSalesPlanningProgram1.
     */
    public RowSet getVO_XXSalesPlanningProgram1() {
        return (RowSet)getAttributeInternal(VO_XXSALESPLANNINGPROGRAM1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_SalesPlanningPoType1.
     */
    public RowSet getVO_SalesPlanningPoType1() {
        return (RowSet)getAttributeInternal(VO_SALESPLANNINGPOTYPE1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_SalesPlanningShipMode1.
     */
    public RowSet getVO_SalesPlanningShipMode1() {
        return (RowSet)getAttributeInternal(VO_SALESPLANNINGSHIPMODE1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_SalesPlanningBookMonth1.
     */
    public RowSet getVO_SalesPlanningBookMonth1() {
        return (RowSet)getAttributeInternal(VO_SALESPLANNINGBOOKMONTH1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_SalesPlanningCurrencyCode1.
     */
    public RowSet getVO_SalesPlanningCurrencyCode1() {
        return (RowSet)getAttributeInternal(VO_SALESPLANNINGCURRENCYCODE1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_SalesPlanningShipTerm1.
     */
    public RowSet getVO_SalesPlanningShipTerm1() {
        return (RowSet)getAttributeInternal(VO_SALESPLANNINGSHIPTERM1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_SalesPlanningYesNo1.
     */
    public RowSet getVO_SalesPlanningYesNo1() {
        return (RowSet)getAttributeInternal(VO_SALESPLANNINGYESNO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_SalesPlanningPOStatus1.
     */
    public RowSet getVO_SalesPlanningPOStatus1() {
        return (RowSet)getAttributeInternal(VO_SALESPLANNINGPOSTATUS1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_SalesPlanningHeader1.
     */
    public RowSet getVO_SalesPlanningHeader1() {
        return (RowSet)getAttributeInternal(VO_SALESPLANNINGHEADER1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_SelectedCustName1.
     */
    public RowSet getVO_SelectedCustName1() {
        return (RowSet)getAttributeInternal(VO_SELECTEDCUSTNAME1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_SelectedCustPoNo1.
     */
    public RowSet getVO_SelectedCustPoNo1() {
        return (RowSet)getAttributeInternal(VO_SELECTEDCUSTPONO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_SelectedSalesContractNo1.
     */
    public RowSet getVO_SelectedSalesContractNo1() {
        return (RowSet)getAttributeInternal(VO_SELECTEDSALESCONTRACTNO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_SelectedDyeingWoNo1.
     */
    public RowSet getVO_SelectedDyeingWoNo1() {
        return (RowSet)getAttributeInternal(VO_SELECTEDDYEINGWONO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_SelectedGriageContractNo1.
     */
    public RowSet getVO_SelectedGriageContractNo1() {
        return (RowSet)getAttributeInternal(VO_SELECTEDGRIAGECONTRACTNO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_XXSalesPlanningPhase1.
     */
    public RowSet getVO_XXSalesPlanningPhase1() {
        return (RowSet)getAttributeInternal(VO_XXSALESPLANNINGPHASE1);
    }
}
