package model.VO;

import HandlerBean.PageListener;

import HandlerBean.UserInfo;

import javax.faces.context.FacesContext;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 01 22:32:06 UZT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_XXSalesPlanningProgramImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
     
    public VO_XXSalesPlanningProgramImpl() {
        
    }


    /**
     * Returns the bind variable value for u.
     * @return bind variable value for u
     */
    public String getu() {
        /*PageListener UserID*/
        //return PageListener.userID;
        //UserInfo ui = new UserInfo();
        //return ui.getUserID();
        FacesContext fctx = FacesContext.getCurrentInstance();
        HttpServletRequest req =
        (HttpServletRequest)fctx.getExternalContext().getRequest();
        String u = (String)req.getSession().getAttribute("userID");
        //return (String)req.getSession().getAttribute("userID");
        return u;
    }

    /**
     * Sets <code>value</code> for bind variable u.
     * @param value value to bind as u
     */
    public void setu(String value) {
        setNamedWhereClauseParam("u", value);
    }

    /**
     * Returns the bind variable value for rsp_id.
     * @return bind variable value for rsp_id
     */
    public String getrsp_id() {
        /*PageListener RespID*/
        //return PageListener.responsibiltyID;
        //UserInfo ui = new UserInfo();
        //return ui.getRespID();
        FacesContext fctx = FacesContext.getCurrentInstance();
        HttpServletRequest req =
        (HttpServletRequest)fctx.getExternalContext().getRequest();
        return (String)req.getSession().getAttribute("respID");
    }

    /**
     * Sets <code>value</code> for bind variable rsp_id.
     * @param value value to bind as rsp_id
     */
    public void setrsp_id(String value) {
        setNamedWhereClauseParam("rsp_id", value);
    }

    /**
     * Returns the bind variable value for resp.
     * @return bind variable value for resp
     */
    public String getresp() {
        /*PageListener Resp*/
        //return PageListener.responsibility;
        FacesContext fctx = FacesContext.getCurrentInstance();
        HttpServletRequest req =
        (HttpServletRequest)fctx.getExternalContext().getRequest();
        return (String)req.getSession().getAttribute("resp");
        //UserInfo ui = new UserInfo();
        //return ui.getResp();
    }

    /**
     * Sets <code>value</code> for bind variable resp.
     * @param value value to bind as resp
     */
    public void setresp(String value) {
        setNamedWhereClauseParam("resp", value);
    }
}
