package model.VO;

import HandlerBean.Bunny;

import HandlerBean.PageListener;

import HandlerBean.UserInfo;

import javax.faces.context.FacesContext;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import model.EO.EO_XXSalesPlanningProgramImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 01 22:32:06 UZT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_XXSalesPlanningProgramRowImpl extends ViewRowImpl {
    
    
    @Override
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        
       

        /*PageListener UserID*/
//                        this.setProgramManager(PageListener.userID);
//                        this.setLastUpdatedBy(new Number(Integer.parseInt(PageListener.userID)));
//                        this.setCreatedBy(new Number(Integer.parseInt(PageListener.userID)));
        
        
                FacesContext fctx = FacesContext.getCurrentInstance();
        HttpServletRequest req =
            (HttpServletRequest)fctx.getExternalContext().getRequest();
        HttpSession session = req.getSession();

        
        this.setProgramManager((String)session.getAttribute("userID"));
        this.setLastUpdatedBy(new Number(Integer.parseInt((String)session.getAttribute("userID"))));
        this.setCreatedBy(new Number(Integer.parseInt((String)session.getAttribute("userID"))));


    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CustAcctId {
            public Object get(VO_XXSalesPlanningProgramRowImpl obj) {
                return obj.getCustAcctId();
            }

            public void put(VO_XXSalesPlanningProgramRowImpl obj,
                            Object value) {
                obj.setCustAcctId((Number)value);
            }
        },
        ProgramId {
            public Object get(VO_XXSalesPlanningProgramRowImpl obj) {
                return obj.getProgramId();
            }

            public void put(VO_XXSalesPlanningProgramRowImpl obj,
                            Object value) {
                obj.setProgramId((Number)value);
            }
        },
        ProgramManager {
            public Object get(VO_XXSalesPlanningProgramRowImpl obj) {
                return obj.getProgramManager();
            }

            public void put(VO_XXSalesPlanningProgramRowImpl obj,
                            Object value) {
                obj.setProgramManager((String)value);
            }
        },
        PrgManager {
            public Object get(VO_XXSalesPlanningProgramRowImpl obj) {
                return obj.getPrgManager();
            }

            public void put(VO_XXSalesPlanningProgramRowImpl obj,
                            Object value) {
                obj.setPrgManager((String)value);
            }
        },
        ProgramName {
            public Object get(VO_XXSalesPlanningProgramRowImpl obj) {
                return obj.getProgramName();
            }

            public void put(VO_XXSalesPlanningProgramRowImpl obj,
                            Object value) {
                obj.setProgramName((String)value);
            }
        },
        ProgramPhase {
            public Object get(VO_XXSalesPlanningProgramRowImpl obj) {
                return obj.getProgramPhase();
            }

            public void put(VO_XXSalesPlanningProgramRowImpl obj,
                            Object value) {
                obj.setProgramPhase((Number)value);
            }
        },
        LastUpdatedBy {
            public Object get(VO_XXSalesPlanningProgramRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(VO_XXSalesPlanningProgramRowImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        },
        CreatedBy {
            public Object get(VO_XXSalesPlanningProgramRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(VO_XXSalesPlanningProgramRowImpl obj,
                            Object value) {
                obj.setCreatedBy((Number)value);
            }
        },
        CustomerName {
            public Object get(VO_XXSalesPlanningProgramRowImpl obj) {
                return obj.getCustomerName();
            }

            public void put(VO_XXSalesPlanningProgramRowImpl obj,
                            Object value) {
                obj.setCustomerName((String)value);
            }
        },
        PhaseName {
            public Object get(VO_XXSalesPlanningProgramRowImpl obj) {
                return obj.getPhaseName();
            }

            public void put(VO_XXSalesPlanningProgramRowImpl obj,
                            Object value) {
                obj.setPhaseName((String)value);
            }
        },
        VO_XXSppArticle {
            public Object get(VO_XXSalesPlanningProgramRowImpl obj) {
                return obj.getVO_XXSppArticle();
            }

            public void put(VO_XXSalesPlanningProgramRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        VO_XXSppSize {
            public Object get(VO_XXSalesPlanningProgramRowImpl obj) {
                return obj.getVO_XXSppSize();
            }

            public void put(VO_XXSalesPlanningProgramRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        VO_XXSppColor {
            public Object get(VO_XXSalesPlanningProgramRowImpl obj) {
                return obj.getVO_XXSppColor();
            }

            public void put(VO_XXSalesPlanningProgramRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        VO_XXSalesPlanningPhase1 {
            public Object get(VO_XXSalesPlanningProgramRowImpl obj) {
                return obj.getVO_XXSalesPlanningPhase1();
            }

            public void put(VO_XXSalesPlanningProgramRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        VO_XXSalesPlanningProgram1 {
            public Object get(VO_XXSalesPlanningProgramRowImpl obj) {
                return obj.getVO_XXSalesPlanningProgram1();
            }

            public void put(VO_XXSalesPlanningProgramRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        VO_ARCustomers1 {
            public Object get(VO_XXSalesPlanningProgramRowImpl obj) {
                return obj.getVO_ARCustomers1();
            }

            public void put(VO_XXSalesPlanningProgramRowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(VO_XXSalesPlanningProgramRowImpl object);

        public abstract void put(VO_XXSalesPlanningProgramRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CUSTACCTID = AttributesEnum.CustAcctId.index();
    public static final int PROGRAMID = AttributesEnum.ProgramId.index();
    public static final int PROGRAMMANAGER =
        AttributesEnum.ProgramManager.index();
    public static final int PRGMANAGER = AttributesEnum.PrgManager.index();
    public static final int PROGRAMNAME = AttributesEnum.ProgramName.index();
    public static final int PROGRAMPHASE = AttributesEnum.ProgramPhase.index();
    public static final int LASTUPDATEDBY =
        AttributesEnum.LastUpdatedBy.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int PHASENAME = AttributesEnum.PhaseName.index();
    public static final int VO_XXSPPARTICLE =
        AttributesEnum.VO_XXSppArticle.index();
    public static final int VO_XXSPPSIZE = AttributesEnum.VO_XXSppSize.index();
    public static final int VO_XXSPPCOLOR =
        AttributesEnum.VO_XXSppColor.index();
    public static final int VO_XXSALESPLANNINGPHASE1 =
        AttributesEnum.VO_XXSalesPlanningPhase1.index();
    public static final int VO_XXSALESPLANNINGPROGRAM1 =
        AttributesEnum.VO_XXSalesPlanningProgram1.index();
    public static final int VO_ARCUSTOMERS1 =
        AttributesEnum.VO_ARCustomers1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VO_XXSalesPlanningProgramRowImpl() {
    }

    /**
     * Gets EO_XXSalesPlanningProgram entity object.
     * @return the EO_XXSalesPlanningProgram
     */
    public EO_XXSalesPlanningProgramImpl getEO_XXSalesPlanningProgram() {
        return (EO_XXSalesPlanningProgramImpl)getEntity(0);
    }


    /**
     * Gets the attribute value for CUST_ACCT_ID using the alias name CustAcctId.
     * @return the CUST_ACCT_ID
     */
    public Number getCustAcctId() {
        return (Number)getAttributeInternal(CUSTACCTID);
    }


    /**
     * Sets <code>value</code> as attribute value for CUST_ACCT_ID using the alias name CustAcctId.
     * @param value value to set the CUST_ACCT_ID
     */
    public void setCustAcctId(Number value) {
        setAttributeInternal(CUSTACCTID, value);
    }

    /**
     * Gets the attribute value for PROGRAM_ID using the alias name ProgramId.
     * @return the PROGRAM_ID
     */
    public Number getProgramId() {
        return (Number)getAttributeInternal(PROGRAMID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROGRAM_ID using the alias name ProgramId.
     * @param value value to set the PROGRAM_ID
     */
    public void setProgramId(Number value) {
        setAttributeInternal(PROGRAMID, value);
    }

    /**
     * Gets the attribute value for PROGRAM_MANAGER using the alias name ProgramManager.
     * @return the PROGRAM_MANAGER
     */
    public String getProgramManager() {
        return (String)getAttributeInternal(PROGRAMMANAGER);
    }

    /**
     * Sets <code>value</code> as attribute value for PROGRAM_MANAGER using the alias name ProgramManager.
     * @param value value to set the PROGRAM_MANAGER
     */
    public void setProgramManager(String value) {
        setAttributeInternal(PROGRAMMANAGER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrgManager.
     * @return the PrgManager
     */
    public String getPrgManager() {
        return (String)getAttributeInternal(PRGMANAGER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrgManager.
     * @param value value to set the  PrgManager
     */
    public void setPrgManager(String value) {
        setAttributeInternal(PRGMANAGER, value);
    }

    /**
     * Gets the attribute value for PROGRAM_NAME using the alias name ProgramName.
     * @return the PROGRAM_NAME
     */
    public String getProgramName() {
        return (String)getAttributeInternal(PROGRAMNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PROGRAM_NAME using the alias name ProgramName.
     * @param value value to set the PROGRAM_NAME
     */
    public void setProgramName(String value) {
        setAttributeInternal(PROGRAMNAME, value);
    }

    /**
     * Gets the attribute value for PROGRAM_PHASE using the alias name ProgramPhase.
     * @return the PROGRAM_PHASE
     */
    public Number getProgramPhase() {
        return (Number)getAttributeInternal(PROGRAMPHASE);
    }

    /**
     * Sets <code>value</code> as attribute value for PROGRAM_PHASE using the alias name ProgramPhase.
     * @param value value to set the PROGRAM_PHASE
     */
    public void setProgramPhase(Number value) {
        setAttributeInternal(PROGRAMPHASE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerName.
     * @return the CustomerName
     */
    public String getCustomerName() {
        return (String)getAttributeInternal(CUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerName.
     * @param value value to set the  CustomerName
     */
    public void setCustomerName(String value) {
        setAttributeInternal(CUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PhaseName.
     * @return the PhaseName
     */
    public String getPhaseName() {
        return (String)getAttributeInternal(PHASENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PhaseName.
     * @param value value to set the  PhaseName
     */
    public void setPhaseName(String value) {
        setAttributeInternal(PHASENAME, value);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link VO_XXSppArticle.
     */
    public RowIterator getVO_XXSppArticle() {
        return (RowIterator)getAttributeInternal(VO_XXSPPARTICLE);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link VO_XXSppSize.
     */
    public RowIterator getVO_XXSppSize() {
        return (RowIterator)getAttributeInternal(VO_XXSPPSIZE);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link VO_XXSppColor.
     */
    public RowIterator getVO_XXSppColor() {
        return (RowIterator)getAttributeInternal(VO_XXSPPCOLOR);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_XXSalesPlanningPhase1.
     */
    public RowSet getVO_XXSalesPlanningPhase1() {
        return (RowSet)getAttributeInternal(VO_XXSALESPLANNINGPHASE1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_XXSalesPlanningProgram1.
     */
    public RowSet getVO_XXSalesPlanningProgram1() {
        return (RowSet)getAttributeInternal(VO_XXSALESPLANNINGPROGRAM1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_ARCustomers1.
     */
    public RowSet getVO_ARCustomers1() {
        return (RowSet)getAttributeInternal(VO_ARCUSTOMERS1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
