package model.VO;

import HandlerBean.PageListener;

import HandlerBean.UserInfo;

import javax.faces.context.FacesContext;

import javax.servlet.http.HttpServletRequest;

import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 08 23:26:05 UZT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_XXSalesPlanningHeaderMgtImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    
    
    public VO_XXSalesPlanningHeaderMgtImpl() {
       
        
    }

    /**
     * Returns the bind variable value for rsp_id.
     * @return bind variable value for rsp_id
     */
    public String getrsp_id() {
        /*PageListener RespID*/
        //return PageListener.responsibiltyID;
        FacesContext fctx = FacesContext.getCurrentInstance();
        HttpServletRequest req =
        (HttpServletRequest)fctx.getExternalContext().getRequest();
        //System.out.println("Resp_id: "+req.getSession().getAttribute("respID"));
        return (String)req.getSession().getAttribute("respID");
        //UserInfo ui = new UserInfo();
        //return ui.getRespID();
    }

    /**
     * Sets <code>value</code> for bind variable rsp_id.
     * @param value value to bind as rsp_id
     */
    public void setrsp_id(String value) {
        setNamedWhereClauseParam("rsp_id", value);
    }

    /**
     * Returns the bind variable value for user_id.
     * @return bind variable value for user_id
     */
    public String getuser_id() {
        /*PageListener UserID*/
        //return PageListener.userID;
        FacesContext fctx = FacesContext.getCurrentInstance();
        HttpServletRequest req =
        (HttpServletRequest)fctx.getExternalContext().getRequest();
        //System.out.println("User: "+req.getSession().getAttribute("userID"));
        return (String)req.getSession().getAttribute("userID");
        //UserInfo ui = new UserInfo();
        //return ui.getUserID();
    }

    /**
     * Sets <code>value</code> for bind variable user_id.
     * @param value value to bind as user_id
     */
    public void setuser_id(String value) {
        setNamedWhereClauseParam("user_id", value);
    }

    /**
     * Returns the variable value for PO_REC_DATE.
     * @return variable value for PO_REC_DATE
     */
    public Timestamp getPO_REC_DATE() {
        return (Timestamp)ensureVariableManager().getVariableValue("PO_REC_DATE");
    }

    /**
     * Sets <code>value</code> for variable PO_REC_DATE.
     * @param value value to bind as PO_REC_DATE
     */
    public void setPO_REC_DATE(Timestamp value) {
        ensureVariableManager().setVariableValue("PO_REC_DATE", value);
    }

    /**
     * Returns the variable value for SHIPMENT_DATE.
     * @return variable value for SHIPMENT_DATE
     */
    public Timestamp getSHIPMENT_DATE() {
        return (Timestamp)ensureVariableManager().getVariableValue("SHIPMENT_DATE");
    }

    /**
     * Sets <code>value</code> for variable SHIPMENT_DATE.
     * @param value value to bind as SHIPMENT_DATE
     */
    public void setSHIPMENT_DATE(Timestamp value) {
        ensureVariableManager().setVariableValue("SHIPMENT_DATE", value);
    }

    /**
     * Returns the variable value for EX_MIL.
     * @return variable value for EX_MIL
     */
    public Timestamp getEX_MIL() {
        return (Timestamp)ensureVariableManager().getVariableValue("EX_MIL");
    }

    /**
     * Sets <code>value</code> for variable EX_MIL.
     * @param value value to bind as EX_MIL
     */
    public void setEX_MIL(Timestamp value) {
        ensureVariableManager().setVariableValue("EX_MIL", value);
    }

    /**
     * Returns the variable value for INSPECTION_DATE.
     * @return variable value for INSPECTION_DATE
     */
    public Timestamp getINSPECTION_DATE() {
        return (Timestamp)ensureVariableManager().getVariableValue("INSPECTION_DATE");
    }

    /**
     * Sets <code>value</code> for variable INSPECTION_DATE.
     * @param value value to bind as INSPECTION_DATE
     */
    public void setINSPECTION_DATE(Timestamp value) {
        ensureVariableManager().setVariableValue("INSPECTION_DATE", value);
    }

    /**
     * Returns the variable value for CONTAINER_BOOKING_DATE.
     * @return variable value for CONTAINER_BOOKING_DATE
     */
    public Timestamp getCONTAINER_BOOKING_DATE() {
        return (Timestamp)ensureVariableManager().getVariableValue("CONTAINER_BOOKING_DATE");
    }

    /**
     * Sets <code>value</code> for variable CONTAINER_BOOKING_DATE.
     * @param value value to bind as CONTAINER_BOOKING_DATE
     */
    public void setCONTAINER_BOOKING_DATE(Timestamp value) {
        ensureVariableManager().setVariableValue("CONTAINER_BOOKING_DATE", value);
    }

    /**
     * Returns the variable value for GREIGE_COMPLETION_DATE.
     * @return variable value for GREIGE_COMPLETION_DATE
     */
    public Timestamp getGREIGE_COMPLETION_DATE() {
        return (Timestamp)ensureVariableManager().getVariableValue("GREIGE_COMPLETION_DATE");
    }

    /**
     * Sets <code>value</code> for variable GREIGE_COMPLETION_DATE.
     * @param value value to bind as GREIGE_COMPLETION_DATE
     */
    public void setGREIGE_COMPLETION_DATE(Timestamp value) {
        ensureVariableManager().setVariableValue("GREIGE_COMPLETION_DATE", value);
    }

    /**
     * Returns the variable value for DYEING_INPUT_DATE.
     * @return variable value for DYEING_INPUT_DATE
     */
    public String getDYEING_INPUT_DATE() {
        return (String)ensureVariableManager().getVariableValue("DYEING_INPUT_DATE");
    }

    /**
     * Sets <code>value</code> for variable DYEING_INPUT_DATE.
     * @param value value to bind as DYEING_INPUT_DATE
     */
    public void setDYEING_INPUT_DATE(String value) {
        ensureVariableManager().setVariableValue("DYEING_INPUT_DATE", value);
    }

    /**
     * Returns the variable value for STITCH_INPUT_DATE.
     * @return variable value for STITCH_INPUT_DATE
     */
    public Timestamp getSTITCH_INPUT_DATE() {
        return (Timestamp)ensureVariableManager().getVariableValue("STITCH_INPUT_DATE");
    }

    /**
     * Sets <code>value</code> for variable STITCH_INPUT_DATE.
     * @param value value to bind as STITCH_INPUT_DATE
     */
    public void setSTITCH_INPUT_DATE(Timestamp value) {
        ensureVariableManager().setVariableValue("STITCH_INPUT_DATE", value);
    }

    /**
     * Returns the variable value for ACCESSORIES_ORDER_DATE.
     * @return variable value for ACCESSORIES_ORDER_DATE
     */
    public String getACCESSORIES_ORDER_DATE() {
        return (String)ensureVariableManager().getVariableValue("ACCESSORIES_ORDER_DATE");
    }

    /**
     * Sets <code>value</code> for variable ACCESSORIES_ORDER_DATE.
     * @param value value to bind as ACCESSORIES_ORDER_DATE
     */
    public void setACCESSORIES_ORDER_DATE(String value) {
        ensureVariableManager().setVariableValue("ACCESSORIES_ORDER_DATE", value);
    }

    /**
     * Returns the variable value for BOOK_MONTH.
     * @return variable value for BOOK_MONTH
     */
    public String getBOOK_MONTH() {
        return (String)ensureVariableManager().getVariableValue("BOOK_MONTH");
    }

    /**
     * Sets <code>value</code> for variable BOOK_MONTH.
     * @param value value to bind as BOOK_MONTH
     */
    public void setBOOK_MONTH(String value) {
        ensureVariableManager().setVariableValue("BOOK_MONTH", value);
    }

    /**
     * Returns the variable value for PROGRAM_NAME.
     * @return variable value for PROGRAM_NAME
     */
    public String getPROGRAM_NAME() {
        return (String)ensureVariableManager().getVariableValue("PROGRAM_NAME");
    }

    /**
     * Sets <code>value</code> for variable PROGRAM_NAME.
     * @param value value to bind as PROGRAM_NAME
     */
    public void setPROGRAM_NAME(String value) {
        ensureVariableManager().setVariableValue("PROGRAM_NAME", value);
    }

    /**
     * Returns the variable value for PROGRAM_MANAGER.
     * @return variable value for PROGRAM_MANAGER
     */
    public String getPROGRAM_MANAGER() {
        return (String)ensureVariableManager().getVariableValue("PROGRAM_MANAGER");
    }

    /**
     * Sets <code>value</code> for variable PROGRAM_MANAGER.
     * @param value value to bind as PROGRAM_MANAGER
     */
    public void setPROGRAM_MANAGER(String value) {
        ensureVariableManager().setVariableValue("PROGRAM_MANAGER", value);
    }

    /**
     * Returns the variable value for CUSTOMER_NAME.
     * @return variable value for CUSTOMER_NAME
     */
    public Number getCUSTOMER_NAME() {
        return (Number)ensureVariableManager().getVariableValue("CUSTOMER_NAME");
    }

    /**
     * Sets <code>value</code> for variable CUSTOMER_NAME.
     * @param value value to bind as CUSTOMER_NAME
     */
    public void setCUSTOMER_NAME(Number value) {
        ensureVariableManager().setVariableValue("CUSTOMER_NAME", value);
    }


    /**
     * Returns the bind variable value for resp.
     * @return bind variable value for resp
     */
    public String getresp() {
        /*PageListener Resp*/
        //return PageListener.responsibility;
        FacesContext fctx = FacesContext.getCurrentInstance();
        HttpServletRequest req =
        (HttpServletRequest)fctx.getExternalContext().getRequest();
        //System.out.println("Resp: "+req.getSession().getAttribute("resp"));
        return (String)req.getSession().getAttribute("resp");
        //UserInfo ui = new UserInfo();
        //return ui.getResp();
    }

    /**
     * Sets <code>value</code> for bind variable resp.
     * @param value value to bind as resp
     */
    public void setresp(String value) {
        setNamedWhereClauseParam("resp", value);
    }
}
